Bashate settings and fixes to various scripts
Indentation was harmonized across the repo. Scripts without shebang have been given one,
the optional `()` in function definitions has been dropped.

Signed-off-by: Jiri Podivin <jpodivin@redhat.com>

diff --git a/dib/iptables/bin/os-iptables-stateful b/dib/iptables/bin/os-iptables-stateful
--- a/dib/iptables/bin/os-iptables-stateful
+++ b/dib/iptables/bin/os-iptables-stateful
@@ -6,7 +6,7 @@
 # not use this file except in compliance with the License. You may obtain
 # a copy of the License at
 #
-#  http://www.apache.org/licenses/LICENSE-2.0
+#    http://www.apache.org/licenses/LICENSE-2.0
 #
 # Unless required by applicable law or agreed to in writing, software
 # distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
@@ -19,7 +19,7 @@ set -o pipefail
 
 SCRIPT_NAME=$(basename $0)
 
-function show_usage () {
+function show_usage {
 
 cat << EOF
 usage: '$SCRIPT_NAME INPUTFILE'
@@ -27,7 +27,7 @@ usage: '$SCRIPT_NAME INPUTFILE'
 Script to configure iptables.
 
 Positional arguments:
-        INPUTFILE    File containing required configuration details.
+                INPUTFILE        File containing required configuration details.
 
 An input file is parsed and iptables rules are configured accordingly.
 Rules are applied idempotently (ie duplicate rules are not created)
@@ -47,26 +47,26 @@ Sample input file contents:
 -I INPUT -p tcp -j stunnel-INPUT
 EOF
 
-  exit 1
-}
-
-function check() {
-  check_chain_name ${@:2}
-  iptables $@ > /dev/null 2>&1
-}
-
-function check_chain_name() {
-  # Verify that a chain name is supplied
-  grep -qEv '^[[:space:]]*-|^[[:space:]]*$' < <(echo $@)
-  if [ $? -ne 0 ]; then
-    echo "$SCRIPT_NAME: bad input (no chain) \"$LINE\""
     exit 1
-  fi
 }
 
-function apply() {
-  iptables $@
-  echo "$SCRIPT_NAME: iptables $@"
+function check {
+    check_chain_name ${@:2}
+    iptables $@ > /dev/null 2>&1
+}
+
+function check_chain_name {
+    # Verify that a chain name is supplied
+    grep -qEv '^[[:space:]]*-|^[[:space:]]*$' < <(echo $@)
+    if [ $? -ne 0 ]; then
+        echo "$SCRIPT_NAME: bad input (no chain) \"$LINE\""
+        exit 1
+    fi
+}
+
+function apply {
+    iptables $@
+    echo "$SCRIPT_NAME: iptables $@"
 }
 
 [ $# -ne 1 ] && show_usage
@@ -74,30 +74,29 @@ function apply() {
 FILE=$1
 
 if [ ! -r $FILE ]; then
-  echo "$SCRIPT_NAME: Cannot read input file ${FILE}."
-  exit 1
+    echo "$SCRIPT_NAME: Cannot read input file ${FILE}."
+    exit 1
 fi
 
-while read LINE
-do
-  CMD=${LINE:0:2}
-  ARGLIST=${LINE:2}
-  case "$CMD" in
-    -A | -I)
-      check -C $ARGLIST || apply $LINE
-      ;;
-    -D)
-      check -C $ARGLIST && apply $LINE
-      ;;
-    -F | -X)
-      check -L $ARGLIST && apply $LINE
-      ;;
-    -N)
-      check -L $ARGLIST || apply $LINE
-      ;;
-    *)
-      echo "$SCRIPT_NAME: bad input \"$LINE\""
-      exit 1
-      ;;
-  esac
+while read LINE; do
+    CMD=${LINE:0:2}
+    ARGLIST=${LINE:2}
+    case "$CMD" in
+        -A | -I)
+            check -C $ARGLIST || apply $LINE
+            ;;
+        -D)
+            check -C $ARGLIST && apply $LINE
+            ;;
+        -F | -X)
+            check -L $ARGLIST && apply $LINE
+            ;;
+        -N)
+            check -L $ARGLIST || apply $LINE
+            ;;
+        *)
+            echo "$SCRIPT_NAME: bad input \"$LINE\""
+            exit 1
+            ;;
+    esac
 done < <(grep -Ev "^[[:space:]]*$|^#" $FILE)
